DROP TABLE IF EXISTS tb_decks_cards;
DROP TABLE IF EXISTS tb_cards;
DROP TABLE IF EXISTS tb_decks;

CREATE TABLE tb_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE tb_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    face_text VARCHAR(255) NOT NULL,
    back_text VARCHAR(255) NOT NULL
);

CREATE TABLE tb_decks_cards (
    id_deck BIGINT NOT NULL,
    id_card BIGINT NOT NULL,
    CONSTRAINT pk_decks_cards PRIMARY KEY (id_deck, id_card),
    CONSTRAINT fk_deck FOREIGN KEY (id_deck) REFERENCES tb_decks(id) ON DELETE CASCADE,
    CONSTRAINT fk_card FOREIGN KEY (id_card) REFERENCES tb_cards(id) ON DELETE CASCADE
);